<template>
    <div class="lg:flex lg:gap-x-8">
        <div>
            <div class="border border-gray-200 rounded mb-6">
                <h2 class="font-bold uppercase text-xs p-4 bg-gray-50 border-b border-gray-200 rounded-t">Setup step 1</h2>
                <div class="my-2 p-4">
                    <b class="block font-bold text-xs">API URL</b>
                    <input type="text" v-model="apiUrl" class="bg-gray-50 rounded border border-gray-200 p-2 mt-1 w-full" />
                </div>
            </div>
            <div class="border border-gray-200 rounded mb-6">
                <h2 class="font-bold uppercase text-xs p-4 bg-gray-50 border-b border-gray-200 rounded-t">Setup step 2</h2>
                <div class="my-2 p-4">
                    <b class="block font-bold text-xs">JWT token</b>
                    <p class="text-gray-400 text-xs">(in production generated by app)</p>
                    <input type="text" v-model="jwt" class="bg-gray-50 rounded border border-gray-200 p-2 mt-1 w-full" />
                </div>
            </div>
            <div class="border border-gray-200 rounded mb-6">
                <h2 class="font-bold uppercase text-xs p-4 bg-gray-50 border-b border-gray-200 rounded-t">Smart Snippets (optional)</h2>
                <div class="my-2 p-4">
                    <b class="block font-bold text-xs">Description of complaint or praise</b>
                    <input type="text" v-model="smartSnippetTopic" class="bg-gray-50 rounded border border-gray-200 p-2 mt-1 w-full" />
                    <b class="block font-bold text-xs mt-4">Response snippet</b>
                    <textarea v-model="smartSnippetReply" rows="3" class="bg-gray-50 rounded border border-gray-200 p-2 w-full h-full mt-1" />
                </div>
            </div>

            <div class="border border-gray-200 rounded mb-6">
                <h2 class="font-bold uppercase text-xs p-4 bg-gray-50 border-b border-gray-200 rounded-t">Signature (optional)</h2>
                <div class="my-2 p-4">
                    <b class="block font-bold text-xs">Personalized signature to end the review</b>
                    <input type="text" v-model="signature" class="bg-gray-50 rounded border border-gray-200 p-2 mt-1 w-full" />
                </div>
            </div>

            <div class="border border-gray-200 rounded mb-6">
                <h2 class="font-bold uppercase text-xs p-4 bg-gray-50 border-b border-gray-200 rounded-t">Business type (optional)</h2>
                <div class="my-2 p-4">
                    <b class="block font-bold text-xs">What business is being reviewed</b>
                    <input type="text" v-model="business_type" class="bg-gray-50 rounded border border-gray-200 p-2 mt-1 w-full" />
                </div>
            </div>

            <div class="border border-gray-200 rounded mb-6">
                <h2 class="font-bold uppercase text-xs p-4 bg-gray-50 border-b border-gray-200 rounded-t">Reply to (optional)</h2>
                <div class="my-2 p-4">
                    <b class="block font-bold text-xs">Person to address in the reply</b>
                    <input type="text" v-model="replyTo" class="bg-gray-50 rounded border border-gray-200 p-2 mt-1 w-full" />
                </div>
            </div>

            <div class="border border-gray-200 rounded mb-6">
                <h2 class="font-bold uppercase text-xs p-4 bg-gray-50 border-b border-gray-200 rounded-t">Language (optional)</h2>
                <div class="my-2 p-4">
                    <b class="block font-bold text-xs">Which language the reply should be drafted in</b>
                    <select v-model="language" class="bg-gray-50 rounded border border-gray-200 p-2 mt-1 w-full">
                        <option value="null">Automatic</option>
                        <option value="de">Deutsch</option>
                        <option value="en">Englisch</option>
                        <option value="es">Spanisch</option>
                    </select>
                </div>
            </div>


            <div class="border border-gray-200 rounded mb-6">
                <h2 class="font-bold uppercase text-xs p-4 bg-gray-50 border-b border-gray-200 rounded-t">Customer review</h2>
                <div class="p-4">
                    <textarea cols="80" rows="10" v-model="input" class="bg-gray-50 rounded border border-gray-200 p-2 mt-1 w-full h-full"></textarea>
                    <button 
                        class="bg-gray-200 border border-gray-700 hover:bg-gray-300 rounded px-2 py-1 mt-2"
                        @click="generateReviewReply"
                        :disabled="isGenerating"
                    >
                        <span v-if="!isGenerating">Generate review reply 🚀</span>
                        <span v-if="isGenerating">Generating reply...</span>
                    </button>
                </div>
            </div>
        </div>
        <div>
            <div class="border border-gray-200 rounded mb-6">
                <h2 class="font-bold uppercase text-xs p-4 bg-gray-50 border-b border-gray-200 rounded-t">Output</h2>
                <div class="p-4">
                    <textarea cols="80" rows="10" v-model="messages" class="bg-gray-50 rounded border border-gray-200 p-2 w-full h-full"></textarea>
                </div>
            </div>

            <div class="border border-gray-200 rounded mt-4">
                <h2 class="font-bold uppercase text-xs p-4 bg-gray-50 border-b border-gray-200 rounded-t">Summary</h2>
                <div class="p-4">
                    <p v-html="metadata.summary">
                    </p>
                </div>
            </div>

            <div class="border border-gray-200 rounded mt-4">
                <h2 class="font-bold uppercase text-xs p-4 bg-gray-50 border-b border-gray-200 rounded-t">Applied Smart Snippets</h2>
                <div class="p-4">
                    <template v-for="(value, key) in metadata">
                        <template v-if="typeof value === 'object'">
                            <template v-for="(innerValue, innerKey) in value" :key="innerKey">
                                <p>
                                    <b> Snippet #{{ parseInt(innerKey) + 1 }}:</b> <span v-html="formatValue(innerValue)"></span>
                                </p>
                            </template>
                        </template>
                    </template>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
import Pusher from 'pusher-js'
import { v4 as uuidv4 } from 'uuid'


export default {
    name: 'ReviewReply',
    data() {
        return {
            input: 'Tanto las instalaciones como el personal estuvieron muy por encima de nuestras expectativas. La ubicación de este hotel es estratégica, en el centro de los lugares que puedes visitar... y si no, el transporte estaba a unos pasos. La única pega fue, que faltaba un desayuno vegano.',
            channelName: '',
            channel: [],
            messages: '',
            metadata: {},
            isGenerating: false,
            isCopied: false,
            apiUrl: '',
            jwt: '',
            smartSnippetTopic: 'no vegan breakfast',
            smartSnippetReply: 'We provide vegan breakfast, but you need to tell us in advance.',
            business_type: 'Syte Hotel Mannheim',
            signature: 'Your Syte Hotel Mannheim',
            replyTo: 'Ingo',
            language: null,
        }
    },
    created() {
        const pusher = new Pusher('695dc511475504db883e', {
            cluster: 'eu'
        })

        this.channel = uuidv4()
        console.info('ℹ️ Pusher session:', pusher.sessionID)
        console.info('ℹ️ Channel:', this.channel)
        
        pusher.bind('message', (data) => {
            console.info({ "ℹ️ Incoming stream message": data })
            if (data === '###stream-start###') {
                this.messages = ''
                return
            }
            if (data === '###stream-end###') {
                return
            }

            if (/^\s*\d+\s*$/.test(data)) {
                data = ' ' + data
            }
            if (/^\s*-\s/.test(data)) {
                data = '\n' + data
            }
            this.messages += data
        })

        pusher.bind('metainfo', (data) => {
            if (data === '###stream-start###') {
                this.metadata = {}
                return
            }
            if (data === '###stream-end###') {
                return
            }

            for (const key in data) {
                const value = data[key]
                if (typeof value === 'object') {
                    for (const innerKey in value) {
                        const innerValue = value[innerKey].replaceAll('\n', '<br>')
                        if (!this.metadata[key]) {
                            this.metadata[key] = {}
                        }
                        this.metadata[key][innerKey] = innerValue
                    }
                } else {
                    const newValue = value.replaceAll('\n', '<br>')
                    if (!this.metadata[key]) {
                        this.metadata[key] = newValue
                    }
                }
            }
        })

        pusher.subscribe(this.channel)
    },
    methods: {
        generateReviewReply() {
            this.isGenerating = true
            this.messages = ''
            this.metadata = {}
            fetch(`${this.apiUrl}/reply/reply-to-feedback-stream?channel_name=${this.channel}`, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'access-token': this.jwt
                },
                body: JSON.stringify({
                    "input_text": this.input,
                    "user_id": "",
                    "profile_id": "",
                    "reply_model_id": "latest-stable-version",
                    "business_type": this.business_type,
                    "tone_of_voice": 1,
                    "response_length": 1,
                    "reply_language": this.language == null ? null : this.language.toUpperCase(),
                    "reply_to": this.replyTo,
                    "sign_offs": [
                        this.signature
                    ],
                    "custom_topic_replies": [{
                        "custom_reply": this.smartSnippetReply,
                        "review_topic": this.smartSnippetTopic,
                        "id": 0
                    }]
                })
            }).then(response => {
                console.log(response)
            }).catch(error => {
                console.error(error)
            }).finally(() => {
                this.isGenerating = false
            })
        },
        formatValue(value) {
            return value.replace(/\n/g, '<br>')
        },
    },
}
</script>
